package main

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/hatyibei/shingan/domain"
	baselineio "github.com/hatyibei/shingan/infrastructure/baseline"
)

// TestSaveBaseline_CreatesFile verifies --save-baseline writes a valid baseline
// JSON containing fingerprints for every finding produced on buggy.json.
func TestSaveBaseline_CreatesFile(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, "out.json")
	baselinePath := filepath.Join(dir, "baseline.json")

	flags := &analyzeFlags{
		input:        testdataPath("buggy.json"),
		output:       "json",
		outputFile:   outPath,
		saveBaseline: baselinePath,
	}
	if _, err := executeAnalyze(flags); err != nil {
		t.Fatalf("executeAnalyze: %v", err)
	}

	b, err := baselineio.Load(baselinePath)
	if err != nil {
		t.Fatalf("load baseline: %v", err)
	}
	if len(b.Findings) == 0 {
		t.Error("expected baseline to contain at least one fingerprint, got 0")
	}
	if b.GeneratedAt.IsZero() {
		t.Error("expected baseline.generated_at to be set")
	}
	for i, fp := range b.Findings {
		if fp.RuleName == "" {
			t.Errorf("fingerprint[%d].rule is empty", i)
		}
	}
}

// TestBaseline_SuppressesExistingFindings verifies that running analyze with a
// baseline generated by the same inputs yields zero findings (everything is
// already in the baseline) and therefore exit code 0.
func TestBaseline_SuppressesExistingFindings(t *testing.T) {
	dir := t.TempDir()
	baselinePath := filepath.Join(dir, "baseline.json")
	firstOut := filepath.Join(dir, "first.json")
	secondOut := filepath.Join(dir, "second.json")

	// Pass 1: generate baseline from buggy.json.
	if _, err := executeAnalyze(&analyzeFlags{
		input:        testdataPath("buggy.json"),
		output:       "json",
		outputFile:   firstOut,
		saveBaseline: baselinePath,
	}); err != nil {
		t.Fatalf("pass 1: %v", err)
	}

	// Pass 2: re-analyze with the baseline applied — expect zero new findings.
	code, err := executeAnalyze(&analyzeFlags{
		input:      testdataPath("buggy.json"),
		output:     "json",
		outputFile: secondOut,
		baseline:   baselinePath,
	})
	if err != nil {
		t.Fatalf("pass 2: %v", err)
	}
	if code != 0 {
		t.Errorf("pass 2 exit code = %d, want 0 (all findings baselined)", code)
	}

	// Confirm the JSON report records zero findings.
	data, err := os.ReadFile(secondOut)
	if err != nil {
		t.Fatalf("read second output: %v", err)
	}
	var report struct {
		Summary struct {
			Total int `json:"total"`
		} `json:"summary"`
		Findings []struct {
			RuleName string `json:"rule"`
		} `json:"findings"`
	}
	if err := json.Unmarshal(data, &report); err != nil {
		t.Fatalf("parse report: %v", err)
	}
	if report.Summary.Total != 0 {
		t.Errorf("summary.total = %d, want 0 after baseline filter", report.Summary.Total)
	}
	if len(report.Findings) != 0 {
		t.Errorf("findings len = %d, want 0 after baseline filter", len(report.Findings))
	}
}

// TestBaseline_SaveAfterFilter verifies that --baseline + --save-baseline used
// together saves only the *new* findings (those not already in the baseline),
// matching the phase2plan pseudocode contract.
func TestBaseline_SaveAfterFilter(t *testing.T) {
	dir := t.TempDir()
	firstBaseline := filepath.Join(dir, "first.json")
	secondBaseline := filepath.Join(dir, "second.json")

	// Pass 1: save a full baseline of buggy.json.
	if _, err := executeAnalyze(&analyzeFlags{
		input:        testdataPath("buggy.json"),
		output:       "json",
		outputFile:   filepath.Join(dir, "out1.json"),
		saveBaseline: firstBaseline,
	}); err != nil {
		t.Fatalf("pass 1: %v", err)
	}

	// Pass 2: re-analyze with baseline applied AND save-baseline set — the
	// new baseline should be empty because there are no new findings.
	if _, err := executeAnalyze(&analyzeFlags{
		input:        testdataPath("buggy.json"),
		output:       "json",
		outputFile:   filepath.Join(dir, "out2.json"),
		baseline:     firstBaseline,
		saveBaseline: secondBaseline,
	}); err != nil {
		t.Fatalf("pass 2: %v", err)
	}

	b, err := baselineio.Load(secondBaseline)
	if err != nil {
		t.Fatalf("load second baseline: %v", err)
	}
	if len(b.Findings) != 0 {
		t.Errorf("second baseline should be empty after baseline filter, got %d fingerprints", len(b.Findings))
	}
}

// TestSince_HEADReturnsZero verifies --since=HEAD returns zero findings because
// `git diff --name-only HEAD..HEAD` is always empty. Skipped if git is
// unavailable or if the test is not running inside a git worktree.
func TestSince_HEADReturnsZero(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not available")
	}
	if out, err := exec.Command("git", "rev-parse", "--git-dir").Output(); err != nil {
		t.Skipf("not in a git repo: %v (%s)", err, out)
	}

	outPath := filepath.Join(t.TempDir(), "out.json")
	code, err := executeAnalyze(&analyzeFlags{
		input:      testdataPath("buggy.json"),
		output:     "json",
		outputFile: outPath,
		since:      "HEAD",
	})
	if err != nil {
		t.Fatalf("executeAnalyze --since=HEAD: %v", err)
	}
	if code != 0 {
		t.Errorf("exit code = %d, want 0 (no files changed since HEAD)", code)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	var report struct {
		Summary struct {
			Total int `json:"total"`
		} `json:"summary"`
	}
	if err := json.Unmarshal(data, &report); err != nil {
		t.Fatalf("parse report: %v", err)
	}
	if report.Summary.Total != 0 {
		t.Errorf("summary.total = %d, want 0 (since=HEAD)", report.Summary.Total)
	}
}

// TestSince_RejectsLeadingDash verifies --since values that start with "-"
// are rejected before reaching git, defending against accidental option
// smuggling like --exec=...
func TestSince_RejectsLeadingDash(t *testing.T) {
	cases := []string{"-x", "--exec=touch /tmp/pwn", "-rev"}
	for _, since := range cases {
		_, err := executeAnalyze(&analyzeFlags{
			input:      testdataPath("buggy.json"),
			output:     "json",
			outputFile: filepath.Join(t.TempDir(), "out.json"),
			since:      since,
		})
		if err == nil {
			t.Errorf("--since=%q: expected rejection, got nil error", since)
		}
	}
}

// TestSince_InvalidRef verifies --since with a bogus ref returns an error.
func TestSince_InvalidRef(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not available")
	}
	if _, err := exec.Command("git", "rev-parse", "--git-dir").Output(); err != nil {
		t.Skip("not in a git repo")
	}

	_, err := executeAnalyze(&analyzeFlags{
		input:      testdataPath("buggy.json"),
		output:     "json",
		outputFile: filepath.Join(t.TempDir(), "out.json"),
		since:      "this-ref-definitely-does-not-exist-xyzzy",
	})
	if err == nil {
		t.Error("expected error for invalid --since ref, got nil")
	}
}

// TestFilterNew verifies the in-memory filter used by --baseline.
func TestFilterNew(t *testing.T) {
	existing := &domain.Baseline{
		Findings: []domain.FindingFingerprint{
			{RuleName: "cycle_detection", NodeID: "loop_body", Message: "cycle detected"},
		},
	}
	findings := []domain.Finding{
		{RuleName: "cycle_detection", NodeID: "loop_body", Message: "cycle detected", Severity: domain.Critical},
		{RuleName: "new_rule", NodeID: "node_x", Message: "brand new", Severity: domain.Warning},
	}
	got := filterNew(findings, existing)
	if len(got) != 1 {
		t.Fatalf("want 1 new finding, got %d", len(got))
	}
	if got[0].RuleName != "new_rule" {
		t.Errorf("want new_rule, got %q", got[0].RuleName)
	}
}

// TestFilterNew_NilBaseline verifies nil baseline is a pass-through.
func TestFilterNew_NilBaseline(t *testing.T) {
	findings := []domain.Finding{{RuleName: "r", NodeID: "n", Message: "m"}}
	got := filterNew(findings, nil)
	if len(got) != 1 {
		t.Errorf("nil baseline should pass through, got %d findings", len(got))
	}
}

// TestFileInAllowlist verifies path matching handles different spellings of
// the same logical file.
func TestFileInAllowlist(t *testing.T) {
	allow := []string{"cmd/shingan/analyze.go"}
	cases := map[string]bool{
		"cmd/shingan/analyze.go":   true,
		"./cmd/shingan/analyze.go": true,
		"cmd/shingan/other.go":     false,
	}
	for in, want := range cases {
		if got := fileInAllowlist(in, allow); got != want {
			t.Errorf("fileInAllowlist(%q) = %v, want %v", in, got, want)
		}
	}
}

// TestBaseline_MissingFile verifies --baseline with a non-existent path errors.
func TestBaseline_MissingFile(t *testing.T) {
	_, err := executeAnalyze(&analyzeFlags{
		input:      testdataPath("buggy.json"),
		output:     "json",
		outputFile: filepath.Join(t.TempDir(), "out.json"),
		baseline:   "/no/such/baseline.json",
	})
	if err == nil {
		t.Error("expected error for missing baseline file, got nil")
	}
}

// TestExistingBehaviour_Unchanged verifies that running analyze without any of
// the new flags yields exactly the same output JSON as before Phase 2-E, i.e.
// backward compatibility is preserved.
func TestExistingBehaviour_Unchanged(t *testing.T) {
	outPath := filepath.Join(t.TempDir(), "out.json")
	code, err := executeAnalyze(&analyzeFlags{
		input:      testdataPath("buggy.json"),
		output:     "json",
		outputFile: outPath,
	})
	if err != nil {
		t.Fatalf("executeAnalyze: %v", err)
	}
	if code != 2 {
		t.Errorf("exit code = %d, want 2 (buggy.json without any diff flags)", code)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	var report struct {
		Summary struct {
			Total    int `json:"total"`
			Critical int `json:"critical"`
		} `json:"summary"`
	}
	if err := json.Unmarshal(data, &report); err != nil {
		t.Fatalf("parse: %v", err)
	}
	if report.Summary.Critical == 0 {
		t.Error("expected critical findings in baseline-less run, got 0")
	}
}
